### ISSUE TITLE
IOS: Blank Screen on TikTok Login

### ISSUE THREAD

**Issue by bigyank** [Raiinmaker/tiktok_login_flutter#1]
It works on Android but for IOS the webview is empty

<img width="1390" alt="Screenshot at Sep 13 15-39-27" src="https://user-images.githubusercontent.com/43530486/189871926-2101510c-5431-4345-afdd-0279a63a7ed4.png">

**Comment by bigyank** [comment]
If anyone is here with the same problem, I found the solution, Please complete the following steps as well

Go to https://developers.tiktok.com/doc/getting-started-ios-quickstart-swift
Step 1: Configure TikTok App Settings for iOS

Go to TikTok Developer App Registration Page to create your app. After approval, you will get the Client Key and Client Secret.
Step 2: Configure Xcode Project

Configure Info.plist

```
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>tiktokopensdk</string>
    <string>tiktoksharesdk</string>
    <string>snssdk1180</string>
    <string>snssdk1233</string>
</array>
<key>TikTokAppID</key>
<string>$TikTokAppID</string>
<key>CFBundleURLTypes</key>
<array>
  <dict>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>$TikTokAppID</string>
    </array>
  </dict>
</array>
```

**Comment by aqueelaboobacker** [comment]
Sorry for not writing this in the documentation. I have not updated the project since I met with a bug in the TikTokOpenSDK for iOS. I'll update the plugin once they resolve it. Thanks.

**Comment by shadyshrif** [comment]
Note that: Replace $TikTokAppID with your App's Client Key

> If anyone is here with the same problem, I found the solution, Please complete the following steps as well
> 
> Go to https://developers.tiktok.com/doc/getting-started-ios-quickstart-swift Step 1: Configure TikTok App Settings for iOS
> 
> Go to TikTok Developer App Registration Page to create your app. After approval, you will get the Client Key and Client Secret. Step 2: Configure Xcode Project
> 
> Configure Info.plist
> 
> ```
> <key>LSApplicationQueriesSchemes</key>
> <array>
>     <string>tiktokopensdk</string>
>     <string>tiktoksharesdk</string>
>     <string>snssdk1180</string>
>     <string>snssdk1233</string>
> </array>
> <key>TikTokAppID</key>
> <string>$TikTokAppID</string>
> <key>CFBundleURLTypes</key>
> <array>
>   <dict>
>     <key>CFBundleURLSchemes</key>
>     <array>
>       <string>$TikTokAppID</string>
>     </array>
>   </dict>
> </array>
> ```
